openapi: 3.0.0
################################################################################
#                              API Information                                 #
################################################################################
info:
  description: "Monty Hall problem"
  version: "1.0.0"
  title: "Monty Hall problem"
  contact:
    email: "sachin97@hotmail.com"

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################

servers:
  - url: http://api.example.com/api
    description: Server description

tags:
- name: "monty hall"
  description: "Solving Monty Hall Problem"

paths:
  /play/{iterations}/{switch}:
    get:
      tags:
      - "user"
      summary: "Solve Monty Hall Problem"
      description: ""
      operationId: "solveMontyHallProblem"
      parameters:
      - name: iterations
        in: "path"
        description: "Number of iterations to perform to solve the problem"
        required: true
        schema: 
          type: integer
      - name: "switch"
        in: "path"
        description: "Whether participant wants to switch"
        required: true
        schema:
          type: boolean
      responses:
        "200":
          description: "successful operation"
          content:
            text/raw:   
              schema:
                type: string
                example: Winning percentage for the given input is 100%!!
        "400":
          description: "Invalid suparameters plied"
        "404":
          description: "Not found"